Amms/Models/Extended/Reservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Amms.Models
{

    public class Reservation
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string EmailID { get; set; }

        public User MyUser { get; set; }
        public List<User> UserList { get; set; }
        public Appointment Myappointment { get; set; }

        public AppointmentService MyappService { get; set; }

        public DateTime AppointmentDate { get; set; }

        public List<Service> ServList { get; set; }

        public Service Myservice { get; set; }

        //   public List<UserAppointment> AppointList { get; set; }
        public Vehicle Myvehicle { get; set; }
        public int SelectedVehicle { get; set; }
        public List<Vehicle> VehicleList { get; set; }
        public Dictionary<int, string> VehicleDropList { get; set; }

    }

}

Amms/Controllers/ResevationController.cs
using Amms.Models;
//using Amms.Models.Helpers;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Amms.Controllers
{
    public class ResevationController : Controller
    {
        //UserHelper hUser;
        ServiceController sController;
        VehicleController vController;
    
        //-------------------Load user's reservation page------------------
        // GET: Resevation
        [HttpGet]
        public ActionResult GetReservation()
        {           
            sController = new ServiceController();
            vController = new VehicleController();

            Reservation app = new Reservation();
                app.UserID = Convert.ToInt32(Session["UserID"]);
                app.FirstName = Session["FirstName"].ToString();
                app.LastName = Session["LastName"].ToString();
                app.Mobile = Session["Mobile"].ToString();
                app.EmailID = Session["Email"].ToString();

                app.VehicleList = vController.GetAllVehicle();
                Dictionary<int, string> dropList = new Dictionary<int, string>();
                foreach (var i in app.VehicleList)
                {
                    if (i.UserID == app.UserID)
                    {
                        dropList.Add(i.VehicleID, i.VehicleNumber);
                    }
                }
                app.VehicleDropList = dropList;

                app.ServList = sController.GetAllService();

            return View("Reservation", app);
        }

        //---------------save reservations placed by user to db-----------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetReservation(Reservation app, DateTime appdate, String apptime)
        {
            sController = new ServiceController();
            vController = new VehicleController();
            Appointment appobj = new Appointment();
            AppointmentService appserobj;

            bool Status = false;
            string message = "";
            int id = Convert.ToInt32(Session["UserID"]);

            using (MyDatabaseEntities dc = new MyDatabaseEntities())
            {
                try
                {
                    appobj.UserID = id;
                    appobj.AppointmentDate = appdate;
                    appobj.AppointmentStartTime = apptime + ":" + "00";

                    DateTime Time = DateTime.ParseExact(apptime, "HH:mm", CultureInfo.InvariantCulture);
                    int hrs = Time.Hour;
                    string minutes = (Time.Minute).ToString();
                    hrs = hrs + 2;
                    string Hrs = hrs.ToString();

                    string time = Hrs + ":" + minutes + ":" + "00";

                    appobj.AppointmentEndTime = time;
                    appobj.AppointmentStatus = "Pending";
                    appobj.VehicleID = 1;
                    app.Myappointment = appobj;

                    dc.Appointments.Add(app.Myappointment);
                    dc.SaveChanges();

                    foreach (var i in app.ServList)
                    {
                        if (i.IsActive == true)
                        {
                            appserobj = new AppointmentService();
                            appserobj.AppointmentID = app.Myappointment.AppointmentID;
                            appserobj.UserID = app.Myappointment.UserID;
                            appserobj.VehicleID = app.Myappointment.VehicleID;

                            appserobj.ServiceID = i.ServiceID;
                            app.MyappService = appserobj;

                            dc.AppointmentServices.Add(app.MyappService);
                            dc.SaveChanges();
                        }
                    }

                    message = "Your Reservation has successfully placed";
                    Status = true;
                }
                catch(Exception e)
                {
                    message = "Error!";
                }
            }

            app.VehicleList = vController.GetAllVehicle();
            Dictionary<int, string> dropList = new Dictionary<int, string>();
            foreach (var i in app.VehicleList)
            {
                if (i.UserID == app.UserID)
                {
                    dropList.Add(i.VehicleID, i.VehicleNumber);
                }
            }
            app.VehicleDropList = dropList;
          
            app.ServList = sController.GetAllService();

            app.UserID = Convert.ToInt32(Session["UserID"]);
            app.FirstName = Session["FirstName"].ToString();
            app.LastName = Session["LastName"].ToString();
            app.Mobile = Session["Mobile"].ToString();
            app.EmailID = Session["Email"].ToString();

            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View("Reservation", app);
        }


          //---------------Load admin's reservation page----------------------

        [HttpGet]
        public ActionResult GetReservationAdmin(int id)
        {
            sController = new ServiceController();
            vController = new VehicleController();
            User user = new User();

            Reservation app = new Reservation();

            using (MyDatabaseEntities dc = new MyDatabaseEntities())
                {
                    user = (from c in dc.Users
                            where c.UserID == id
                            select c).FirstOrDefault();
                }
                app.UserID = user.UserID;
                app.FirstName = user.FirstName;
                app.LastName = user.LastName;
                app.Mobile = user.Mobile;
                app.EmailID = user.EmailID;
            

            app.VehicleList = vController.GetAllVehicle();
            Dictionary<int, string> dropList = new Dictionary<int, string>();
            foreach (var i in app.VehicleList)
            {
                if (i.UserID == app.UserID)
                {
                    dropList.Add(i.VehicleID, i.VehicleNumber);
                }
            }
            app.VehicleDropList = dropList;

            app.ServList = sController.GetAllService();

            return View("Reservation", app);
        }

        //-----------------save reservations placed by admin to db

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetReservationAdmin(Reservation app, DateTime appdate, String apptime)
        {
            sController = new ServiceController();
            vController = new VehicleController();
            Appointment appobj = new Appointment();
            AppointmentService appserobj;
            User user = new User();

            bool Status = false;
            string message = "";
            int id = Convert.ToInt32(Session["UserID"]);

            using (MyDatabaseEntities dc = new MyDatabaseEntities())
            {
                appobj.UserID = id;
                appobj.AppointmentDate = appdate;
                appobj.AppointmentStartTime = apptime + ":" + "00";

                DateTime Time = DateTime.ParseExact(apptime, "HH:mm", CultureInfo.InvariantCulture);
                int hrs = Time.Hour;
                string minutes = (Time.Minute).ToString();
                hrs = hrs + 2;
                string Hrs = hrs.ToString();

                string time = Hrs + ":" + minutes + ":" + "00";

                appobj.AppointmentEndTime = time;
                appobj.AppointmentStatus = "Pending";
                appobj.VehicleID = 1;
                app.Myappointment = appobj;

                dc.Appointments.Add(app.Myappointment);
                dc.SaveChanges();

                foreach (var i in app.ServList)
                {
                    if (i.IsActive == true)
                    {
                        appserobj = new AppointmentService();
                        appserobj.AppointmentID = app.Myappointment.AppointmentID;
                        appserobj.UserID = app.Myappointment.UserID;
                        appserobj.VehicleID = app.Myappointment.VehicleID;

                        appserobj.ServiceID = i.ServiceID;
                        app.MyappService = appserobj;

                        dc.AppointmentServices.Add(app.MyappService);
                        dc.SaveChanges();
                    }
                }

                message = "success ";
                Status = true;

                     user = (from c in dc.Users
                        where c.UserID == id
                        select c).FirstOrDefault();
            
                         app.UserID = user.UserID;
                         app.FirstName = user.FirstName;
                         app.LastName = user.LastName;
                         app.Mobile = user.Mobile;
                         app.EmailID = user.EmailID;

                app.VehicleList = vController.GetAllVehicle();
            }

          
            Dictionary<int, string> dropList = new Dictionary<int, string>();
            foreach (var i in app.VehicleList)
            {
                if (i.UserID == app.UserID)
                {
                    dropList.Add(i.VehicleID, i.VehicleNumber);
                }
            }
            app.VehicleDropList = dropList;

            app.ServList = sController.GetAllService();


            ViewBag.Message = message;
            ViewBag.Status = Status;
            //return RedirectToAction("AddUser", "Admin");
            return View("Registration", app);
        }

        //-------------------------List all reservation details for admins reservation panel-------------
        public List<Appointment> GetAllAppointments()
        {

Amms/Views/Resevation/Reservation.cshtml
@model Amms.Models.Reservation
@using DayPilot.Web.Mvc.Events.Calendar;
@using DayPilot.Web.Mvc.Enums.Calendar;

@{
	ViewBag.Title = "Reservation";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/Calendar/lib/dayPilot/daypilot-all.min.js")" type="text/javascript"></script>

<head>
	<style>
		lable {
			color: #a6a6a6;
			font-family: 'Open Sans', sans-serif;
			font-size: 13px;
		}
	</style>
</head>

<body>
	@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
	{
		if (ViewBag.Message != null)
		{
			if (ViewBag.Type == true)
			{
				<script type="text/javascript">

            window.onload = function () {
                alert("@ViewBag.Message");

				};
				</script>
			}

			else
			{
				<script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");

				 };
				</script>
			}
		}

	}


	@using (Html.BeginForm("GetReservation", "Resevation", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()

		<!-- #page-title end -->
		<section>
			<h2>Reservations</h2>
			<div class="clearfix mb-150">
				<div class="container">
					<form class="mb-12">
						<div class="row">
							<div class="col-sm-3">


								<div class="form-group">
									@*@Html.EditorFor(model => model.FirstName, new { @class = "control-label col-md-2" })*@
									<label type="text" class="form-control" id="firstname" style="height: 35px">First Name: @Model.FirstName</label>
								</div>
								<div class="form-group">
									@*@Html.EditorFor(model => model.LastName, new { @class = "control-label col-md-2" })*@
									<label type="text" class="form-control" id="lastname" style="height: 35px">Last Name: @Model.LastName</label>
								</div>
								<div class="form-group">
									@*@Html.EditorFor(model => model.Mobile, new { @class = "control-label col-md-2" })*@
									<label type="text" class="form-control" id="mobile" style="height: 35px">Mobile: @Model.Mobile</label>
								</div>
								<div class="form-group">
									@*@Html.EditorFor(model => model.EmailID, new { @class = "control-label col-md-2" })*@
									<label type="text" class="form-control" id="email" style="height: 35px">Email: @Model.EmailID</label>
								</div>

								<div class="form-group">
									<label type="text" class="form-control" id="vehicle" style="height: 35px"> Select Your Vehicle</label>
									<div class="col-md-10">
										@Html.DropDownListFor(model => model.Myvehicle.VehicleID, new SelectList(Model.VehicleDropList, "Key", "Value"), "Select Vehicle")
										@Html.ValidationMessageFor(model => model.Myvehicle.VehicleID, "", new { @class = "text-danger" })
									</div>
								</div>

								<div class="form-group">
									<label> </label>
								</div>



								<div class="form-group">
									<label for="text" id="AppointmentD">Appointment Date: </label><input type="date" id="AppDate" name="appdate">

								</div>
								<div class="form-group">
									<label type="text" id="AppointmentT">Appointment Time: </label> <input type="time" id="AppTime" name="apptime">

								</div>
								<div class="form-group ">
									<label type="text" class="form-control" id="Service" style="height: 35px">Select your Services</label>
									@for (int u = 0; u < Model.ServList.Count; u++)
									{
										@Html.HiddenFor(model => model.ServList[u].ServiceName);
										@Html.HiddenFor(model => model.ServList[u].ServiceID);
										@Html.HiddenFor(model => model.ServList[u].ServiceDescription);
										@Html.HiddenFor(model => model.ServList[u].ServicePrice);
										@Html.HiddenFor(model => model.ServList[u].ServiceTime);
										@Html.HiddenFor(model => model.ServList[u].ServiceImage);
										@Html.CheckBoxFor(model => model.ServList[u].IsActive, new { @class = "form-check-input" }) <span>- @Model.ServList[u].ServiceName</span><br>;

										if(ViewBag.Status==true)
										{
											Model.ServList[u].IsActive = false;
										}

									}
								</div>
							</div>
							<div class="col-sm-9">
								@* calendar *@
								<div class="about-accordion">
									<div class="panel-group accordion" id="accordion02" role="tablist" aria-multiselectable="true">
										<div class="panel panel-default">
											<div class="panel-heading" role="tab" id="headingTwo">
												<h4>
													<label type="text" class="form-control" id="time" style="height: 35px" >Allocated Time Slots</label>
													<a class="accordion-toggle collapsed" role="button" data-toggle="collapse" data-parent="#accordion02" href="#collapse02-2" aria-expanded="false" aria-controls="collapse02-2"> </a>
												</h4>
											</div>
											<div id="collapse02-2"  role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false">
												<div class="panel-body">
													<div style="display: flex">

														<div style="margin-right: 10px;">

															@Html.DayPilotNavigator("nav", new DayPilotNavigatorConfig
													   {
														   ShowMonths = 3,
														   SkipMonths = 3
													   })
														</div>

														<div style="flex-grow: 1;">

															@Html.DayPilotCalendar("dp_week", new DayPilotCalendarConfig
													   {
														   BackendUrl = Url.Content("~/Calendar/Week"),
														   ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
														   TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
														   TimeRangeSelectedJavaScript = "create(start, end)"

													   })
														</div>
													</div>

												</div>
											</div>

										</div>
									</div>
								</div>

							</div>
						</div>




						<button type="submit" class="btn btn-primary text-center mt-30">Reserve</button>
					</form>
				</div>
			</div>
		</section>
	}
</body>

Amms/Views/Resevation/Reservation1.cshtml
@model Amms.Models.Reservation
@using DayPilot.Web.Mvc.Events.Calendar;
@using DayPilot.Web.Mvc.Enums.Calendar;

@{
	ViewBag.Title = "Reservation";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/Calendar/lib/dayPilot/daypilot-all.min.js")" type="text/javascript"></script>

<head>
	<style>
		lable {
			color: #a6a6a6;
			font-family: 'Open Sans', sans-serif;
			font-size: 13px;
		}
	</style>
</head>

<body>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
	if (ViewBag.Message != null)
	{
		<div class="alert alert-success">
			<strong>Your Reservation is successfully placed</strong>
		</div>
	}
}


@using (Html.BeginForm("GetReservation", "Resevation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<!-- #page-title end -->
	<section>
		<h2>Reservations</h2>
		<div class="clearfix mb-150">
			<div class="container">
				<form class="mb-0">
					<div class="form-group">
						<label type="text" class="form-control" id="firstname">First Name: @Model.FirstName</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="lastname">Last Name: @Model.LastName</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="mobile">Mobile: @Model.Mobile</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="email">Email: @Model.EmailID</label>
					</div>

					<div class="form-group">
						<label type="text" class="form-control" id="vehicle"> Select Your Vehicle</label>
						<div class="col-md-10">
							@Html.DropDownListFor(m => m.Myvehicle.VehicleID, new SelectList(Model.VehicleDropList, "Key", "Value"), "Select Vehicle")
							@Html.ValidationMessageFor(model => model.Myvehicle.VehicleID, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<label> </label>
					</div>

					<div class="about-accordion">
						<div class="panel-group accordion" id="accordion02" role="tablist" aria-multiselectable="true">
							<div class="panel panel-default">
								<div class="panel-heading" role="tab" id="headingTwo">
									<h4>
										<label type="text" class="form-control" id="time">Allocated Time Slots</label>
										<a class="accordion-toggle collapsed" role="button" data-toggle="collapse" data-parent="#accordion02" href="#collapse02-2" aria-expanded="false" aria-controls="collapse02-2"> </a>
									</h4>
								</div>
								<div id="collapse02-2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false">
									<div class="panel-body">
										<div style="display: flex">

											<div style="margin-right: 10px;">

												@Html.DayPilotNavigator("nav", new DayPilotNavigatorConfig
										   {
											   ShowMonths = 3,
											   SkipMonths = 3
										   })
											</div>

											<div style="flex-grow: 1;">

												@Html.DayPilotCalendar("dp_week", new DayPilotCalendarConfig
										   {
											   BackendUrl = Url.Content("~/Calendar/Week"),
											   ViewType = DayPilot.Web.Mvc.Enums.Calendar.ViewType.Week,
											   TimeRangeSelectedHandling = TimeRangeSelectedHandlingType.JavaScript,
											   TimeRangeSelectedJavaScript = "create(start, end)"

										   })
											</div>
										</div>

									</div>
								</div>

							</div>
						</div>
					</div>

					<div class="form-group">
						<label for="text" id="AppointmentD">Appointment Date: </label><input type="date" id="AppDate" name="appdate">

					</div>
					<div class="form-group">
						<label type="text" id="AppointmentT">Appointment Time: </label> <input type="time" id="AppTime" name="apptime">

					</div>
					<div class="form-group ">
						<label type="text" class="form-control" id="Service">Select your Services</label>
						@foreach (var u in Model.ServList)
						{
							<input class="form-check-input" type="checkbox" id="@u.ServiceID"> @u.ServiceName<br />
							@*@Html.CheckBoxFor(m => m.StaticCheckbox[i].Selected, new { @class = "flat" })

							@Html.DisplayFor(m => m.Myservice.ServiceName)

							@Html.HiddenFor(m => m.Myservice.ServiceID)*@

						}
					</div>

					<button type="submit" class="btn btn-primary text-center mt-30">Reserve</button>
				</form>
			</div>
		</div>
	</section>
	}
</body>

Amms/Views/Resevation/Test.cshtml
@model Amms.Models.Reservation
@using DayPilot.Web.Mvc.Events.Calendar;
@using DayPilot.Web.Mvc.Enums.Calendar;

@{
	ViewBag.Title = "Reservation";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.0/jquery.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Content/Calendar/lib/dayPilot/daypilot-all.min.js")" type="text/javascript"></script>

<head>
	<style>
		lable {
			color: #a6a6a6;
			font-family: 'Open Sans', sans-serif;
			font-size: 13px;
		}
	</style>
</head>

<body>
@if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
{
	if (ViewBag.Message != null)
	{
		<div class="alert alert-success">
			<strong>Your Reservation is successfully placed</strong>
		</div>
	}
}


@using (Html.BeginForm("Checkbox", "Resevation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<!-- #page-title end -->
	<section>
		<h2>Reservations</h2>
		<div class="clearfix mb-150">
			<div class="container">
				<form class="mb-0">
					@*<div class="form-group">
						<label type="text" class="form-control" id="firstname">First Name: @Model.FirstName</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="lastname">Last Name: @Model.LastName</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="mobile">Mobile: @Model.Mobile</label>
					</div>
					<div class="form-group">
						<label type="text" class="form-control" id="email">Email: @Model.EmailID</label>
					</div>*@

					<div class="form-group">
						<label type="text" class="form-control" id="vehicle"> Select Your Vehicle</label>
						<div class="col-md-10">
							@Html.DropDownListFor(m => m.Myvehicle.VehicleID, new SelectList(Model.VehicleDropList, "Key", "Value"), "Select Vehicle")
							@Html.ValidationMessageFor(model => model.Myvehicle.VehicleID, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<label> </label>
					</div>

				

					<div class="form-group">
						<label for="text" id="AppointmentD">Appointment Date: </label><input type="date" id="AppDate" name="appdate">

					</div>
					<div class="form-group">
						<label type="text" id="AppointmentT">Appointment Time: </label> <input type="time" id="AppTime" name="apptime">

					</div>
					<div class="form-group ">
						<label type="text" class="form-control" id="Service">Select your Services</label>
						@foreach (var u in Model.ServList)
						{
							<input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="@u.ServiceID"> @u.ServiceName<br />
						}
					</div>

					<button type="submit" class="btn btn-primary text-center mt-30">Reserve</button>
				</form>
			</div>
		</div>
	</section>
	}
</body>